# """
# Django settings for employee_management project.

# Generated by 'django-admin startproject' using Django 4.2.20.
# """

# from pathlib import Path
# import os
# import dj_database_url
# from pathlib import Path


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-o5^8l=)fh)la8p#azru&7!r@@#&o=lr)c@&e1_16aly2*22(s4'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# # ✅ Corrected Allowed Hosts
# ALLOWED_HOSTS = ['localhost', '127.0.0.1']
# DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"
# SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-secret-key")
# ALLOWED_HOSTS = ["*"]  # Later replace * with your Render domain for security


# # Application definition
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'employee',
#     'corsheaders',  # ✅ Added for CORS
# ]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',          # ✅ Must be at the top
#     'django.middleware.common.CommonMiddleware',      # ✅ Should come right after CORS
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'employee_management.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'employee_management.wsgi.application'

# # Database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'railway',
#         'USER': 'root',
#         'PASSWORD' : 'pXGUajoZPESSodfvvBFYOfuEbnQNNCyl',
#         'HOST' : 'caboose.proxy.rlwy.net',
#         'PORT' : '25794',
#         'OPTIONS' : {
#             'init_command' : "SET sql_mode='STRICT_TRANS_TABLES'"
#         }
#     }
# }

# # Password validation
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# # Internationalization
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True

# # Static files (CSS, JavaScript, Images)
# STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# # Default primary key field type
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # ✅ CORS Configuration
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # React frontend
# ]

# CORS_ALLOW_CREDENTIALS = True  # ✅ If using cookies or JWT
# # CORS_ALLOW_ALL_ORIGINS = True  # ⚠️ Uncomment only for quick local testing

"""
Django settings for employee_management project.
Generated by 'django-admin startproject' using Django 4.2.20.
"""

import os
from pathlib import Path
import dj_database_url

# ---------------------------------------------
# Basic Setup
# ---------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------
# Security
# ---------------------------------------------
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-secret-key")
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"
ALLOWED_HOSTS = ["*"]  # Replace * with your Render domain later

# ---------------------------------------------
# Installed Apps
# ---------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'employee',
    'corsheaders',
]

# ---------------------------------------------
# Middleware
# ---------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # ✅ Serve static files
    'corsheaders.middleware.CorsMiddleware',         # ✅ Enable CORS
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---------------------------------------------
# URLs & WSGI
# ---------------------------------------------
ROOT_URLCONF = 'employee_management.urls'
WSGI_APPLICATION = 'employee_management.wsgi.application'

# ---------------------------------------------
# Templates
# ---------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ---------------------------------------------
# Database (✅ your original Railway MySQL)
# ---------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'railway',
        'USER': 'root',
        'PASSWORD': 'pXGUajoZPESSodfvvBFYOfuEbnQNNCyl',
        'HOST': 'caboose.proxy.rlwy.net',
        'PORT': '25794',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}

# ---------------------------------------------
# Password Validation
# ---------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ---------------------------------------------
# Internationalization
# ---------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ---------------------------------------------
# Static Files (CSS, JS, Images)
# ---------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ---------------------------------------------
# Default Primary Key Field
# ---------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------
# CORS Settings
# ---------------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # React frontend (for local dev)
]
CORS_ALLOW_CREDENTIALS = True

